const DISEASE_SPECIALTY_MAP = {
  'Heart attack': 'Cardiology',
  Hypertension: 'Cardiology',
  Hypoglycemia: 'General Practice',
  'Bronchial Asthma': 'Pulmonology',
  Pneumonia: 'Pulmonology',
  Tuberculosis: 'Pulmonology',
  'Common Cold': 'General Practice',
  Malaria: 'Infectious Disease',
  Typhoid: 'Infectious Disease',
  Dengue: 'Infectious Disease',
  AIDS: 'Infectious Disease',
  'Paralysis (brain hemorrhage)': 'Neurology',
  Migraine: 'Neurology',
  '(vertigo) Paroymsal  Positional Vertigo': 'Neurology',
  Diabetes: 'Endocrinology',
  Hypothyroidism: 'Endocrinology',
  Hyperthyroidism: 'Endocrinology',
  Jaundice: 'Gastroenterology',
  'Hepatitis A': 'Gastroenterology',
  'Hepatitis B': 'Gastroenterology',
  'Hepatitis C': 'Gastroenterology',
  'Hepatitis D': 'Gastroenterology',
  'Hepatitis E': 'Gastroenterology',
  'Alcoholic hepatitis': 'Gastroenterology',
  'Chronic cholestasis': 'Gastroenterology',
  GERD: 'Gastroenterology',
  'Peptic ulcer diseae': 'Gastroenterology',
  Gastroenteritis: 'Gastroenterology',
  'Urinary tract infection': 'Urology',
  'Fungal infection': 'Dermatology',
  Acne: 'Dermatology',
  Psoriasis: 'Dermatology',
  'Chicken pox': 'Infectious Disease',
  Impetigo: 'Dermatology',
  'Drug Reaction': 'General Practice',
  Allergy: 'General Practice',
  Arthritis: 'Rheumatology',
  Osteoarthristis: 'Rheumatology',
  'Cervical spondylosis': 'Orthopedics',
  'Varicose veins': 'Vascular Surgery',
  'Dimorphic hemmorhoids(piles)': 'General Surgery',
};

module.exports = DISEASE_SPECIALTY_MAP;
